name: Build, Push, and Deploy Docker image to ACR

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/**/*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "tag=${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "tag=${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:prod" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image (prod or dev)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tag }}

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Container App Secrets (dev)
        run: |
          az containerapp secret set \
            --name yonchee-bot-dev \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --secrets \
              azure-form-recognizer-endpoint=${{ secrets.AZURE_FORM_RECOGNIZER_ENDPOINT }} \
              azure-form-recognizer-key=${{ secrets.AZURE_FORM_RECOGNIZER_KEY }} \
              azure-speech-api-key=${{ secrets.AZURE_SPEECH_API_KEY }} \
              azure-region=${{ secrets.AZURE_REGION }} \
              telegram-api-token-dev=${{ secrets.TELEGRAM_API_TOKEN_DEV }}

      - name: Deploy to Azure Container App (dev)
        run: |
          az containerapp update \
            --name yonchee-bot-dev \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:dev \
            --set-env-vars \
              BOT_ENV=dev \
              TELEGRAM_API_TOKEN_DEV=secretref:telegram-api-token-dev \
              AZURE_FORM_RECOGNIZER_ENDPOINT=secretref:azure-form-recognizer-endpoint \
              AZURE_FORM_RECOGNIZER_KEY=secretref:azure-form-recognizer-key \
              AZURE_SPEECH_API_KEY=secretref:azure-speech-api-key \
              AZURE_REGION=secretref:azure-region

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Container App Secrets (prod)
        run: |
          az containerapp secret set \
            --name yonchee-bot-prod \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --secrets \
              azure-form-recognizer-endpoint=${{ secrets.AZURE_FORM_RECOGNIZER_ENDPOINT }} \
              azure-form-recognizer-key=${{ secrets.AZURE_FORM_RECOGNIZER_KEY }} \
              azure-speech-api-key=${{ secrets.AZURE_SPEECH_API_KEY }} \
              azure-region=${{ secrets.AZURE_REGION }} \
              telegram-api-token-prod=${{ secrets.TELEGRAM_API_TOKEN_PROD }}

      - name: Deploy to Azure Container App (prod)
        run: |
          az containerapp update \
            --name yonchee-bot-prod \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:prod \
            --set-env-vars \
              BOT_ENV=prod \
              TELEGRAM_API_TOKEN_PROD=secretref:telegram-api-token-prod \
              AZURE_FORM_RECOGNIZER_ENDPOINT=secretref:azure-form-recognizer-endpoint \
              AZURE_FORM_RECOGNIZER_KEY=secretref:azure-form-recognizer-key \
              AZURE_SPEECH_API_KEY=secretref:azure-speech-api-key \
              AZURE_REGION=secretref:azure-region