name: Build, Push, and Deploy Docker image to ACR

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/**/*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v3

      - name: Set image tags
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::8}"
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          TAGS=""
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            TAGS="${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:dev"
            TAGS="$TAGS,${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:${SHORT_SHA}"
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            TAGS="${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:prod"
            TAGS="$TAGS,${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:latest"
            TAGS="$TAGS,${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:${SHORT_SHA}"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image (prod or dev)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tags }}

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App (dev)
        run: |
          az containerapp update \
            --name yonchee-bot-dev \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:${{ needs.build-and-push.outputs.short_sha }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App (prod)
        run: |
          az containerapp update \
            --name yonchee-bot-prod \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/yonchee-bot:${{ needs.build-and-push.outputs.short_sha }}